-- DELETE DATABASE if exists
DROP DATABASE IF EXISTS stage_airlines
GO
-- CREATE DATABASE stage_airlines 
CREATE DATABASE stage_airlines
GO
USE stage_airlines
GO

-- DELETE TABLES IF EXISTS 
DROP TABLE IF EXISTS airlines_stage;
DROP TABLE IF EXISTS airports_stage;
DROP TABLE IF EXISTS flights_stage;

GO

-- CREATE TABLE stage_airlines.airlines
CREATE TABLE [dbo].[airlines_stage](
    IATA_CODE CHAR(3) NULL,
    AIRLINE VARCHAR(200)) NULL
);

GO

-- CREATE TABLE stage_airlines.airports
CREATE TABLE [dbo].[airports_stage](
    IATA_CODE CHAR(3) NULL,
    AIRPORT VARCHAR(100) NULL,
    CITY VARCHAR(100) NULL,
    STATE CHAR(2) NULL,
    COUNTRY VARCHAR(100) NULL,
    LATITUDE FLOAT NULL,
    LONGITUDE FLOAT NULL
);

GO

-- CREATE TABLE stage_airlines.flights
CREATE TABLE [dbo].[flights_stage](
   flight_date DATE NULL,
   AIRLINE CHAR(3) NULL,
   FLIGHT_NUMBER CHAR(6) NULL,
   TAIL_NUMBER VARCHAR(6) NULL,
   ORIGIN_AIRPORT CHAR(3) NULL,
   DESTINATION_AIRPORT CHAR(3) NULL,
   SCHEDULED_DEPARTURE DATETIME NULL,
   DEPARTURE_TIME DATETIME NULL,
   DEPARTURE_DELAY INT NULL,
   TAXI_OUT INT NULL,
   WHEELS_OFF DATETIME NULL,
   SCHEDULED_TIME INT NULL,
   ELAPSED_TIME INT NULL,
   AIR_TIME INT NULL,
   DISTANCE INT NULL,
   WHEELS_ON DATETIME NULL,
   TAXI_IN INT NULL,
   SCHEDULED_ARRIVAL DATETIME NULL,
   ARRIVAL_TIME DATETIME NULL,
   ARRIVAL_DELAY INT NULL,
   DIVERTED BIT NULL,
   CANCELLED BIT NULL,
   CANCELLATION_REASON VARCHAR(100) NULL,
   AIR_SYSTEM_DELAY INT NULL,
   SECURITY_DELAY INT NULL,
   AIRLINE_DELAY INT NULL,
   LATE_AIRCRAFT_DELAY INT NULL,
   WEATHER_DELAY INT NULL,
   CREATED DATETIME NULL,
   MODIFIED DATETIME NULL
);  
