-- DELETE DATABASE if exists
USE master;
GO
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'stage_airlines')
BEGIN
    ALTER DATABASE stage_airlines SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE stage_airlines;
END
GO
-- CREATE DATABASE stage_airlines 
CREATE DATABASE stage_airlines
GO
USE stage_airlines
GO

-- DELETE TABLES IF EXISTS 
DROP TABLE IF EXISTS airlines_stg;
DROP TABLE IF EXISTS airports_stg;
DROP TABLE IF EXISTS flights_stg_1;
DROP TABLE IF EXISTS flights_stg_2;
DROP TABLE IF EXISTS flights_stg_3;

GO

-- CREATE TABLE stg_airlines.airlines
CREATE TABLE [dbo].[airlines_stg] (
    IATA_CODE VARCHAR(10) PRIMARY KEY,
    Airline VARCHAR(255)
);

-- =============================
-- 4. CREATE TABLE: airport
-- =============================
CREATE TABLE [dbo].[airports_stg] (
    IATA_CODE VARCHAR(10) PRIMARY KEY,
    AIRPORT VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(100),
    LATITUDE DECIMAL(12,9),
    LONGITUDE DECIMAL(12,9)
);


-- =============================
-- 5. CREATE TABLE TEMPLATE for flights
-- =============================
CREATE TABLE [dbo].[flights_stg_1] (
    DATE DATE,
    AIRLINE VARCHAR(10),
    FLIGHT_NUMBER INT,
    TAIL_NUMBER VARCHAR(20),
    ORIGIN_AIRPORT CHAR(10),
    DESTINATION_AIRPORT CHAR(10),
    SCHEDULED_DEPARTURE CHAR(10),
    DEPARTURE_TIME CHAR(10),
    DEPARTURE_DELAY FLOAT,
    TAXI_OUT FLOAT,
    WHEELS_OFF CHAR(10),
    SCHEDULED_TIME FLOAT,
    ELAPSED_TIME FLOAT,
    AIR_TIME FLOAT,
    DISTANCE FLOAT,
    WHEELS_ON CHAR(10),
    TAXI_IN FLOAT,
    SCHEDULED_ARRIVAL CHAR(10),
    ARRIVAL_TIME CHAR(10),
    ARRIVAL_DELAY FLOAT,
    DIVERTED INT,
    CANCELLED INT,
    CANCELLATION_REASON VARCHAR(1),
    AIR_SYSTEM_DELAY FLOAT,
    SECURITY_DELAY FLOAT,
    AIRLINE_DELAY FLOAT,
    LATE_AIRCRAFT_DELAY FLOAT,
    WEATHER_DELAY FLOAT,
    CREATED DATETIME2,
    MODIFIED DATETIME2
);


CREATE TABLE [dbo].[flights_stg_2] (
    DATE DATE,
    AIRLINE VARCHAR(10),
    FLIGHT_NUMBER INT,
    TAIL_NUMBER VARCHAR(20),
    ORIGIN_AIRPORT CHAR(10),
    DESTINATION_AIRPORT CHAR(10),
    SCHEDULED_DEPARTURE CHAR(10),
    DEPARTURE_TIME CHAR(10),
    DEPARTURE_DELAY FLOAT,
    TAXI_OUT FLOAT,
    WHEELS_OFF CHAR(10),
    SCHEDULED_TIME FLOAT,
    ELAPSED_TIME FLOAT,
    AIR_TIME FLOAT,
    DISTANCE FLOAT,
    WHEELS_ON CHAR(10),
    TAXI_IN FLOAT,
    SCHEDULED_ARRIVAL CHAR(10),
    ARRIVAL_TIME CHAR(10),
    ARRIVAL_DELAY FLOAT,
    DIVERTED INT,
    CANCELLED INT,
    CANCELLATION_REASON VARCHAR(1),
    AIR_SYSTEM_DELAY FLOAT,
    SECURITY_DELAY FLOAT,
    AIRLINE_DELAY FLOAT,
    LATE_AIRCRAFT_DELAY FLOAT,
    WEATHER_DELAY FLOAT,
    CREATED DATETIME2,
    MODIFIED DATETIME2
);

CREATE TABLE [dbo].[flights_stg_3] (
    DATE DATE,
    AIRLINE VARCHAR(10),
    FLIGHT_NUMBER INT,
    TAIL_NUMBER VARCHAR(20),
    ORIGIN_AIRPORT CHAR(10),
    DESTINATION_AIRPORT CHAR(10),
    SCHEDULED_DEPARTURE CHAR(10),
    DEPARTURE_TIME CHAR(10),
    DEPARTURE_DELAY FLOAT,
    TAXI_OUT FLOAT,
    WHEELS_OFF CHAR(10),
    SCHEDULED_TIME FLOAT,
    ELAPSED_TIME FLOAT,
    AIR_TIME FLOAT,
    DISTANCE FLOAT,
    WHEELS_ON CHAR(10),
    TAXI_IN FLOAT,
    SCHEDULED_ARRIVAL CHAR(10),
    ARRIVAL_TIME CHAR(10),
    ARRIVAL_DELAY FLOAT,
    DIVERTED INT,
    CANCELLED INT,
    CANCELLATION_REASON VARCHAR(1),
    AIR_SYSTEM_DELAY FLOAT,
    SECURITY_DELAY FLOAT,
    AIRLINE_DELAY FLOAT,
    LATE_AIRCRAFT_DELAY FLOAT,
    WEATHER_DELAY FLOAT,
    CREATED DATETIME2,
    MODIFIED DATETIME2
);

-- DELETE TABLES IF EXISTS 
TRUNCATE TABLE airlines_stg;
TRUNCATE TABLE airports_stg;
TRUNCATE TABLE flights_stg_1;
TRUNCATE TABLE flights_stg_2;
TRUNCATE TABLE flights_stg_3;

SELECT * FROM airlines_stg
SELECT * FROM airports_stg
SELECT * FROM flights_stg_1
SELECT * FROM flights_stg_2
SELECT * FROM flights_stg_3